Добавлены базовые классы, реализован интерфейс IEmployee, для работы со списком сотрудников
Alex6288/Course_work pull request #1
Opened 2021-05-12 10:00 UTC by Alex6288

Далее планирую реализовать доступ к файлам информации по логину и паролю, а также реализовать интерфейс IReport, далее вывод все в вайлы

2021-05-20 11:52 UTC, revers-back requested changes
В целом ок, но нужно сделать через паттерн MVP разберем на след занятии

2021-05-20 11:52 UTC, revers-back commented on .idea/.gitignore
> +/shelf/
для генерации git ignore используем сервис

2021-05-20 11:52 UTC, revers-back commented on .idea/.gitignore
> +/shelf/
https://www.toptal.com/developers/gitignore

2021-05-20 11:52 UTC, revers-back commented on .idea/Course_work.iml
> +  <component name="NewModuleRootManager" inherit-compiler-output="true">
не должно быть в коммите

2021-05-20 11:52 UTC, revers-back commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_15" project-jdk-name="openjdk-15" project-jdk-type="JavaSDK">
не должно быть в коммите

2021-05-20 11:52 UTC, revers-back commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
не должно быть в коммите

2021-05-20 11:52 UTC, revers-back commented on .idea/uiDesigner.xml
> +  <component name="Palette2">
не должно быть в коммите

2021-05-20 11:52 UTC, revers-back commented on src/src/Employee.java
> +import java.math.BigDecimal;
зачем везде паке src src????

2021-05-20 11:52 UTC, revers-back commented on src/src/Employee.java
> +        Scanner scanner = new Scanner(System.in);
смешивается доменная модель и логика UI должно быть отдельно

2021-05-20 11:52 UTC, revers-back commented on src/src/EmployeeAccountingSystem.java
> +    }
пустых методов быть не должно либо должна быть пометка //todo

2021-05-20 11:52 UTC, revers-back commented on src/src/EmployeeAccountingSystem.java
> +public class EmployeeAccountingSystem implements IEmployee, IReport, IAccountingSystem {
Если это хранилище, то должно быть название Repositort или Dao

2021-05-21 09:18 UTC, Alex6288 commented
Изменения произведены

2021-05-21 09:20 UTC, Alex6288 commented on .idea/Course_work.iml
> +  <component name="NewModuleRootManager" inherit-compiler-output="true">
удалять эти файлы из запушенных через git rm?

2021-05-28 14:10 UTC, merged